services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      DIRECT_URL: ${DIRECT_URL}
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      RESEND_API_KEY: ${RESEND_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    restart: always
