services:
  app:
    build:
      context: .
    image: capstone-app-express
    stdin_open: true
    ports:
      - '3000:3000'
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    environment:
      - NODE_ENV=development
